# version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # React
      - "5000:5000" # Flask
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      NODE_ENV: development
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: tracker_user
      MYSQL_PASSWORD: example #TODO: Create & update this password
      MYSQL_DB: satisfactory_tracker
    depends_on:
      - mysql
    command: npm start
  
  mysql:
    image: mysql:8.0
    environment:      
      MYSQL_ROOT_PASSWORD: example #TODO: Create & update this password
      MYSQL_DATABASE: satisfactory_tracker
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: